server:
  port: 38080

spring:
  datasource:
    url: jdbc:mysql://144.202.72.147:3306/mal?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml