server:
  port: 38080

spring:
  datasource:
    url: jdbc:mysql://144.202.72.147:3306/mal?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    show-sql: true

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
logging:
  level:
    com:
     qilin:
       mall:
         mbg:
          mapper: DEBUG
